import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {createDemoStore,lessons,questions,learners} from './store.js';
import './demo.css';

function openStore(){try{return createDemoStore(window.localStorage);}catch{return createDemoStore(null);}}
const store=openStore();
const roles={student:'التلميذ',instructor:'الأستاذ',manager:'مدير المدرسة'};
const pages={today:'اليوم',learn:'التعلم',practice:'التدريب',progress:'التقدم',school:'المتابعة',assistant:'المساعد'};
const getPage=()=>Object.hasOwn(pages,location.hash.slice(1))?location.hash.slice(1):'today';

function Scene({moving=false}){
 return <div className={'demo-scene '+(moving?'moving':'')}><svg viewBox="0 0 620 270" role="img" aria-label="مشهد توضيحي: سيارة زرقاء فاليمين، وسيارة صفراء فاليسار">
  <rect width="620" height="270" rx="28" fill="#e5f3f2"/><circle cx="510" cy="62" r="30" fill="#f8cc70"/>
  <path d="M0 185h620" stroke="#c3d9d8" strokeWidth="120"/><path d="M0 185h620" stroke="white" strokeWidth="3" strokeDasharray="20 17"/>
  <g className="car-blue" transform="translate(400 111)"><rect width="110" height="45" rx="12" fill="#0a5d7a"/><path d="M20 0l18-22h35L90 0" fill="#29abe2"/><circle cx="23" cy="46" r="12" fill="#173447"/><circle cx="86" cy="46" r="12" fill="#173447"/></g>
  <g className="car-gold" transform="translate(100 204)"><rect width="110" height="39" rx="12" fill="#f5a623"/><path d="M20 0l18-20h35L90 0" fill="#ffd67d"/><circle cx="23" cy="40" r="11" fill="#173447"/><circle cx="86" cy="40" r="11" fill="#173447"/></g>
  <g fill="#8cbcac"><circle cx="72" cy="55" r="22"/><circle cx="114" cy="72" r="16"/><circle cx="560" cy="237" r="16"/></g>
 </svg><span>رسم أصلي توضيحي · ماشي وضعية امتحان</span></div>;
}
function Stat({value,label}){return <div className="demo-stat"><strong>{value}</strong><span>{label}</span></div>;}
function App(){
 const [state,setState]=useState(store.getState),[page,setPage]=useState(getPage),[lesson,setLesson]=useState(null),[step,setStep]=useState(0),[notice,setNotice]=useState(''),[student,setStudent]=useState('amina'),[taskLesson,setTaskLesson]=useState('follow'),[example,setExample]=useState(null);
 const main=useRef(null);
 useEffect(()=>{const change=()=>{setPage(getPage());if(getPage()!=='learn')setLesson(null);};window.addEventListener('hashchange',change);return()=>window.removeEventListener('hashchange',change);},[]);
 function send(action){setState(store.dispatch(action));}
 function go(next){location.hash=next;setPage(next);setLesson(null);setNotice('');main.current?.focus();window.scrollTo({top:0});}
 function changeRole(role){send({type:'role',role});go(role==='student'?'today':'school');}
 const read=state.read.amina.length,answered=Object.keys(state.answers).length,score=questions.filter(q=>state.answers[q.id]===q.answer).length;
 const myTasks=state.tasks.filter(t=>t.student==='amina');
 const menu=state.role==='student'?['today','learn','practice','progress','assistant']:['school','assistant'];
 function startLesson(id){setLesson(lessons.find(l=>l.id===id));setStep(0);setPage('learn');location.hash='learn';window.scrollTo({top:0});}
 return <div className="demo-app">
  <div className="demo-disclosure"><span>نسخة عرض تفاعلية</span> بيانات اصطناعية محفوظة فمتصفحك فقط. بلا حساب حقيقي ولا اتصال AI.</div>
  <header className="demo-header"><a href="#today" onClick={()=>go('today')} aria-label="PerminIA الرئيسية"><img src="/brand/perminia-logo.svg" alt="PerminIA"/></a><a className="demo-github" href="https://github.com/hajjoub-abdelkabir/perminia" target="_blank" rel="noreferrer">الكود على GitHub ↗</a></header>
  <section className="demo-rolebar" aria-label="تجربة الأدوار"><div><small>شوف الفكرة من جهة</small><div className="demo-roles">{Object.entries(roles).map(([role,label])=><button key={role} aria-pressed={state.role===role} onClick={()=>changeRole(role)}>{label}</button>)}</div></div><button className="demo-reset" onClick={()=>{if(window.confirm('نرجعو غير بيانات هاد التجربة للبداية؟')){send({type:'reset'});go('today');}}}>↺ إعادة التجربة</button></section>
  <div className="demo-layout"><aside className="demo-sidebar"><span className="demo-school">مدرسة أطلس <small>مدرسة اصطناعية</small></span><nav aria-label="التنقل الرئيسي">{menu.map(p=><button key={p} aria-current={page===p?'page':undefined} onClick={()=>go(p)}>{pages[p]}<span>←</span></button>)}</nav><div className="demo-side-note">خطوة صغيرة اليوم،<br/><strong>فهم أحسن غداً.</strong><span>✦</span></div></aside>
  <main ref={main} tabIndex={-1} className="demo-main"><div className="demo-breadcrumb">فضاء {roles[state.role]} <span>/</span> {pages[page]}</div>
   {!store.isPersistent()&&<p className="demo-warning" role="status">المتصفح ما سمحش بالحفظ. تقدر تجرّب، ولكن التقدم غادي يضيع ملي تسد الصفحة.</p>}
   {notice&&<p className="demo-success" role="status">{notice}</p>}
   {page==='today'&&<><section className="demo-hero"><div><span className="demo-eyebrow">من الحفظ للفهم</span><h1>أمينة، كل خطوة<br/>كتفتح ليك <em>طريق.</em></h1><p>تعلم بصري، تدريب، ومتابعة مع الأستاذ.<br/>جرّب كيفاش كتربط PerminIA هاد الرحلة.</p><button className="demo-primary" onClick={()=>startLesson('observe')}>ابدأ خطوة اليوم <span>←</span></button></div><div className="demo-hero-art"><div className="demo-orbit"/><div className="demo-bot"><i/><i/><b>⌣</b></div><span className="demo-art-label">شوف · جرّب · افهم ✦</span></div></section>
    <div className="demo-stats"><Stat value={`${read}/3`} label="دروس قريتي فالديمو"/><Stat value={`${answered}/3`} label="أجوبة فهاد التجربة"/><Stat value={myTasks.filter(t=>!t.done).length} label="مهام تنتظر الإنجاز"/></div>
    <div className="demo-section-title"><h2>الخطوة ديالك اليوم</h2><span>برنامج توضيحي</span></div><div className="demo-two"><section className="demo-card"><span className="demo-pill">من الأستاذ</span><h3>المهام ديالك</h3>{myTasks.map(t=><div className="demo-task" key={t.id}><strong>{lessons.find(l=>l.id===t.lesson).title}</strong><span>{t.done?'✓ تأكد الإنجاز':state.read.amina.includes(t.lesson)?'القراءة سالات، أكد الإنجاز':'باقي خاص القراءة'}</span><button onClick={()=>t.done?startLesson(t.lesson):state.read.amina.includes(t.lesson)?send({type:'complete',id:t.id}):startLesson(t.lesson)}>{t.done?'مراجعة':state.read.amina.includes(t.lesson)?'تأكيد الإنجاز':'فتح الدرس'} ←</button></div>)}</section><section className="demo-card demo-dark"><span className="demo-eyebrow">علاش هاد المشروع؟</span><h3>ماشي غير سلسلة<br/>وجواب صحيح.</h3><p>الفكرة هي نعرفو فين كاينة الصعوبة، نقترحو خطوة مفيدة، ونعطيو للأستاذ رؤية على المتابعة.</p><button onClick={()=>changeRole('instructor')}>جرّب جهة الأستاذ ←</button></section></div></>}
   {page==='learn'&&!lesson&&<><div className="demo-page-title"><span className="demo-eyebrow">رحلة التعلم</span><h1>فكرة وحدة. خطوة لقدّام.</h1><p>دروس تعريفية أصلية باش تجرّب الواجهة؛ ماشي منهج بيرمي معتمد.</p></div><div className="demo-lesson-list">{lessons.map((l,i)=><button className="demo-lesson" key={l.id} onClick={()=>{setLesson(l);setStep(0);}}><span className="demo-lesson-number">{state.read.amina.includes(l.id)?'✓':`0${i+1}`}</span><div><small>{l.category} · {l.minutes} دقايق</small><h2>{l.title}</h2><p>{l.intro}</p></div><b>←</b></button>)}</div></>}
   {page==='learn'&&lesson&&<section className="demo-card demo-focus"><button className="demo-back" onClick={()=>setLesson(null)}>→ جميع الدروس</button><span className="demo-eyebrow">{lesson.category} · الفكرة {step+1} من 3</span><h1>{lesson.title}</h1><progress max="3" value={step+1} aria-label="خطوات القراءة"/><Scene moving={false}/><p className="demo-reading">{lesson.steps[step]}</p><div className="demo-actions"><button disabled={step===0} onClick={()=>setStep(n=>n-1)}>السابق</button><button className="demo-primary" onClick={()=>{if(step<2)setStep(n=>n+1);else{send({type:'read',lesson:lesson.id});setNotice('تحفظات القراءة فهاد المتصفح. رجع لليوم باش تأكد المهمة، أو جرّب التدريب.');setLesson(null);}}}>{step<2?'متابعة ←':'حفظ القراءة ✓'}</button></div></section>}
   {page==='practice'&&<Practice state={state} send={send}/>}
   {page==='progress'&&<><div className="demo-page-title"><span className="demo-eyebrow">الأثر ديال خطواتك</span><h1>كل رقم عندو معنى.</h1><p>هاد الأرقام جاية من تفاعلاتك فالديمو فقط؛ ما كتقيسش الاستعداد للبيرمي.</p></div><div className="demo-stats"><Stat value={`${read}/3`} label="دروس مقروءة"/><Stat value={`${score}/${answered}`} label="أجوبة صحيحة فالمحاكاة"/><Stat value={myTasks.filter(t=>t.done).length} label="مهام تأكد إنجازها"/></div><section className="demo-card"><h2>خريطة خطواتك</h2>{lessons.map(l=><div className="demo-progress-row" key={l.id}><span>{l.title}</span><progress value={state.read.amina.includes(l.id)?1:0} max="1" aria-label={l.title}/><b>{state.read.amina.includes(l.id)?'مقروء':'مازال'}</b></div>)}<p className="demo-muted">فالنسخة المتكاملة، الإتقان كيعتمد على أجوبة متنوعة ومحتوى معتمد. القراءة بوحدها ماشي إتقان.</p></section></>}
   {page==='school'&&<><div className="demo-page-title"><span className="demo-eyebrow">{state.role==='manager'?'رؤية المدرسة':'توجيه أقرب للتلميذ'}</span><h1>{state.role==='manager'?'مدرستك، بنظرة واضحة.':'شنو الخطوة المناسبة اليوم؟'}</h1><p>بروفايلات اصطناعية. جرّب المهمة مع أمينة وبدّل لجهة التلميذ باش تشوفها.</p></div><div className="demo-stats"><Stat value="3" label="تلاميذ اصطناعيين"/><Stat value={state.tasks.filter(t=>!t.done).length} label="مهام مفتوحة"/><Stat value={state.tasks.filter(t=>t.done).length} label="مهام منجزة"/></div><div className="demo-two"><section className="demo-card"><h2>التلاميذ</h2>{learners.map(l=><button className={'demo-pupil '+(student===l.id?'selected':'')} key={l.id} onClick={()=>setStudent(l.id)}><span className="demo-avatar">{l.initial}</span><span><strong>{l.name}</strong><small>{l.tag} · سيناريو</small></span><b>←</b></button>)}</section><section className="demo-card"><span className="demo-pill">ملف توضيحي</span><h2>{learners.find(l=>l.id===student).name}</h2><p>{state.read[student].length} دروس مقروءة · {state.tasks.filter(t=>t.student===student&&t.done).length} مهام منجزة</p>{state.role==='manager'?<><p>الإسناد: {state.unassigned.includes(student)?'غير مسند':learners.find(l=>l.id===student).teacher}</p><button className="demo-secondary" onClick={()=>{send({type:'assignment',student});setNotice('تبدل الإسناد فالمحاكاة فقط.');}}>{state.unassigned.includes(student)?'إعادة الإسناد':'إزالة الإسناد التجريبي'}</button></>:<><label className="demo-label">الخطوة المقترحة<select value={taskLesson} onChange={e=>setTaskLesson(e.target.value)}>{lessons.map(l=><option value={l.id} key={l.id}>{l.title}</option>)}</select></label><button className="demo-primary" onClick={()=>{send({type:'assign',student,lesson:taskLesson});setNotice('المهمة موجودة فالتجربة. إلا اخترتي أمينة، بدل لجهة التلميذ باش تكملها.');}}>إسناد مهمة ←</button></>}{state.tasks.filter(t=>t.student===student).map(t=><div className="demo-task" key={t.id}><strong>{lessons.find(l=>l.id===t.lesson).title}</strong><span>{t.done?'✓ منجزة':'○ مفتوحة'}</span></div>)}</section></div></>}
   {page==='assistant'&&<><div className="demo-page-title"><span className="demo-eyebrow">مساعد قريب من اللغة ديالك</span><h1>نفهمو الفكرة، بالدارجة.</h1><p>هنا غير أمثلة مكتوبة مسبقاً. ما كاين حتى اتصال OpenAI أو Groq فهاد العرض.</p></div><section className="demo-card demo-chat"><div className="demo-chat-message">مرحبا! فالمنتج المتكامل، المساعد كيستعمل سياق المحادثة ومراجع الدروس. اختار مثال باش تشوف طريقة العرض.</div>{['كيفاش كتحفظو التقدم؟','شنو دور الأستاذ؟'].map((q,i)=><button className="demo-example" key={q} onClick={()=>setExample(i)}>{q} ←</button>)}{example!==null&&<div className="demo-chat-message answer"><span className="demo-pill">مثال توضيحي · ماشي جواب AI حي</span><p>{example===0?'فهاد الديمو، التقدم كيبقى غير فمتصفحك. فالنسخة المحلية المتكاملة، القراءة والأجوبة كيتحفظو فـPostgreSQL ومرتبطين بالحساب والمدرسة.':'الأستاذ كيتابع القراءة والمهام، وكيقترح خطوة مناسبة. إكمال مهمة ماشي بالضرورة إتقان؛ خاص دليل إضافي على الفهم.'}</p></div>}<a href="https://github.com/hajjoub-abdelkabir/perminia#what-you-can-try" target="_blank" rel="noreferrer">كيفاش خدام الربط الحقيقي؟ ↗</a></section></>}
   <footer className="demo-footer"><strong>PerminIA</strong><span>MVP تقني · React / FastAPI / PostgreSQL</span><p>هاد العرض كيوضح تجربة المنتج. اعتماد المحتوى وتجربة مدرسة فعلية هما المرحلة الموالية.</p></footer>
  </main></div>
 </div>;
}
function Practice({state,send}){
 const [started,setStarted]=useState(false),[choice,setChoice]=useState(null),[deadline,setDeadline]=useState(null),[seconds,setSeconds]=useState(30);
 const q=questions.find(x=>!(x.id in state.answers));
 useEffect(()=>{setChoice(null);if(!q||!started)return;const expires=Date.now()+30000;setDeadline(expires);setSeconds(30);const tick=()=>{const left=Math.max(0,Math.ceil((expires-Date.now())/1000));setSeconds(left);if(!left)send({type:'answer',id:q.id,value:-1});};const timer=setInterval(tick,250);return()=>clearInterval(timer);},[q?.id,started]);
 if(!q)return <section className="demo-card demo-result"><span className="demo-result-star">✦</span><span className="demo-eyebrow">نهاية المحاكاة</span><h1>كل جواب، فرصة نفهمو.</h1><p>{questions.filter(x=>state.answers[x.id]===x.answer).length} من 3 فهاد المثال فقط.</p>{questions.map(x=><details key={x.id}><summary>{state.answers[x.id]===x.answer?'✓':state.answers[x.id]===-1?'○':'↺'} {x.prompt}</summary><p>{x.why}</p></details>)}<button className="demo-primary" onClick={()=>{send({type:'retry'});setStarted(false);setDeadline(null);}}>تجربة جديدة ↺</button></section>;
 return <><div className="demo-page-title"><span className="demo-eyebrow">تدريب توضيحي · 3 أسئلة</span><h1>شوف المشهد. جرّب الفهم.</h1><p>العداد والتصحيح هنا محاكاة داخل المتصفح، وماشي اختبار رسمي أو توقيت من الخادم.</p></div><section className="demo-card"><Scene/>{!started?<div className="demo-quiz-start"><h2>واجد تجرب؟</h2><p>30 ثانية لكل سؤال. اختار وأكد، ومن بعد شوف التفسير. تحديث الصفحة يوقف الجولة حتى تضغط البداية من جديد.</p><button className="demo-primary" onClick={()=>setStarted(true)}>بدء المحاكاة ←</button></div>:<><div className="demo-question-head"><span>السؤال {questions.indexOf(q)+1} من 3</span><b role="timer">{seconds} ث</b></div><h2>{q.prompt}</h2><fieldset className="demo-choices"><legend>اختار الجواب</legend>{q.choices.map((label,i)=><label key={label} className={choice===i?'chosen':''}><input type="radio" name={q.id} checked={choice===i} onChange={()=>setChoice(i)}/><span>{label}</span></label>)}</fieldset><button className="demo-primary" disabled={choice===null||seconds===0} onClick={()=>{if(Date.now()>=deadline)send({type:'answer',id:q.id,value:-1});else send({type:'answer',id:q.id,value:choice});}}>تأكيد الإجابة ←</button></>}</section></>;
}
createRoot(document.getElementById('root')).render(<App/>);
