import React,{useEffect,useState} from 'react';
import {schoolRequest} from './school-api';
const label={pending:'بانتظار التفعيل',expired:'منتهية',revoked:'ملغاة',used:'مفعّلة'};
const role={student:'تلميذ',instructor:'أستاذ'};
const date=v=>new Date(v).toLocaleString('ar-MA');
function Secret({value,expires,title}){
 return <div className="school-invitation" role="status"><strong>{title}</strong><input aria-label={title} value={value} readOnly dir="ltr" onFocus={e=>e.target.select()}/><small>صالح حتى {date(expires)}</small><p>الرمز كيبان غير دابا. نسخه وعطيه غير لصاحب الحساب. ما تسيفط حتى بريد أوتوماتيكياً.</p></div>;
}
export function RecoveryControl({member}){
 const [confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState(null);
 async function issue(e){e.preventDefault();setBusy(true);setError('');setResult(null);try{setResult(await schoolRequest('/recovery',{membership_id:member.id,identity_confirmed:confirmed}));}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <details className="account-support"><summary>استرجاع الحساب</summary><p>لـ {member.display_name} · <bdi>{member.email}</bdi></p><p>تأكد من هوية صاحب الحساب قبل ما تعطيه الرمز. الرمز صالح ساعة ولمرة وحدة. إصدار رمز جديد كيلغي الرمز السابق؛ كلمة السر كتبدل غير ملي صاحب الحساب يستعملو.</p><form onSubmit={issue}><label className="support-check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} required/>تأكدت من هوية صاحب الحساب</label><button className="secondary" disabled={!confirmed||busy}>{busy?'جارٍ التحضير…':'إنشاء رمز الاسترجاع'}</button></form>{error&&<p role="alert">{error}</p>}{result&&<Secret title="رمز الاسترجاع" value={result.recovery_code} expires={result.expires_at}/>}<p>صاحب الحساب يختار «نسيت كلمة المرور؟» فصفحة الدخول. تغيير الكلمة كيسد الجلسات القديمة، وما كيمسحش التقدم.</p></details>;
}
export default function InvitationManager({revision}){
 const [items,setItems]=useState(null),[offset,setOffset]=useState(0),[refresh,setRefresh]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false),[result,setResult]=useState(null),[message,setMessage]=useState('');
 useEffect(()=>{let current=true;setError('');setItems(null);schoolRequest('/invitations?offset='+offset).then(d=>current&&setItems(d.items)).catch(e=>current&&setError(e.message));return()=>{current=false;};},[offset,refresh,revision]);
 async function act(inv,action){setBusy(true);setError('');setResult(null);setMessage('');try{const d=await schoolRequest('/invitations/'+action,{invitation_id:inv.id,expected_version:inv.version});if(action==='renew')setResult(d);else setMessage('تلغات الدعوة. الرمز القديم ما بقاش كيخدم.');setRefresh(n=>n+1);}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section className="school-card"><h2>متابعة الدعوات</h2><p>إلا ضاع الرمز أو تسالا وقتو، جدد الدعوة. الرمز القديم كيتلغى مباشرة. الدعوة اللي تفعّلات ما كتتجددش؛ استعمل استرجاع الحساب من لائحة المستخدمين.</p>{error&&<p role="alert">{error}<button className="secondary" onClick={()=>setRefresh(n=>n+1)}>تحديث</button></p>}{message&&<p role="status">{message}</p>}{result&&<Secret title={'رمز الدعوة الجديد · '+result.email} value={result.invitation_code} expires={result.expires_at}/>}{!items?!error&&<p role="status">كنحمّلو الدعوات…</p>:!items.length?<p>ما كايناش دعوات فهاد الصفحة.</p>:items.map(i=><article className="school-task" key={i.id}><bdi>{i.email}</bdi> <span className="school-chip">{role[i.target_role]} · {label[i.state]}</span><small>نهاية الصلاحية: {date(i.expires_at)}</small>{['pending','expired'].includes(i.state)&&<div><button className="secondary" disabled={busy} onClick={()=>act(i,'renew')}>تجديد الرمز</button><button className="school-text-button" disabled={busy} onClick={()=>act(i,'revoke')}>إلغاء الدعوة</button></div>}</article>)}<div className="school-inline"><button className="secondary" disabled={busy||offset===0} onClick={()=>setOffset(n=>Math.max(0,n-50))}>السابق</button><span>الصفحة {offset/50+1}</span><button className="secondary" disabled={busy||!items||items.length<50} onClick={()=>setOffset(n=>n+50)}>التالي</button></div></section>;
}
