import React,{useState} from 'react';
import {stoppingDistances} from './distance-model';
import './concept-scenes.css';

const names=['قف','إعطاء الأسبقية','طريق ذات أولوية','ملتقى أسبقية اليمين'];
function Sign({index}){return <svg viewBox="0 0 200 200" role="img" aria-label={names[index]}><circle cx="100" cy="100" r="96" fill="#fff"/>{index===0?<><polygon points="65,15 135,15 185,65 185,135 135,185 65,185 15,135 15,65" fill="#cf2637" stroke="white" strokeWidth="6"/><text x="100" y="115" textAnchor="middle" fill="white" fontWeight="900" fontSize="43">قف</text></>:index===1?<polygon points="20,30 180,30 100,174" fill="white" stroke="#cf2637" strokeWidth="17" strokeLinejoin="round"/>:index===2?<><path d="m100 14 86 86-86 86-86-86Z" fill="white" stroke="#374c53" strokeWidth="2"/><path d="m100 30 70 70-70 70-70-70Z" fill="#f8d138"/></>:<><polygon points="100,20 185,172 15,172" fill="white" stroke="#cf2637" strokeWidth="15" strokeLinejoin="round"/><path d="m75 95 50 50m0-50-50 50" stroke="#202f34" strokeWidth="12" strokeLinecap="round"/></>}</svg>;}

export function SignSteps({step,review,onStep}){
 const [selected,setSelected]=useState(0),[guess,setGuess]=useState(null);
 const index=review?selected:Math.min(step,3);
 return <section className="sign-workshop"><div className="stage-eyebrow"><span>عينك على العلامة</span><span>{review?'قارن وتذكّر':`${index+1} / 4`}</span></div><div className="sign-workshop-main"><div className="sign-display" key={index}><Sign index={index}/></div><div><h3>{names[index]}</h3><p>{review?'رجع قارن الأشكال، ومن بعد جرّب السؤال لتحت.':'ركز فالشكل والاتجاه ديال العلامة. الشرح اللي لتحت كيتبدل معاها.'}</p><span className="sign-shape">{['ثمانية الأضلاع','مثلث مقلوب','شكل مُعين','مثلث مع تقاطع'][index]}</span></div></div><div className="sign-picker" aria-label="اختيار علامة">{names.map((name,i)=><button key={name} aria-pressed={i===index} onClick={()=>{setSelected(i);if(!review)onStep(i);}}><Sign index={i}/><span>{name}</span></button>)}</div>{review&&<div className="concept-check"><h4>شكون فيهم عندها ثمانية الأضلاع؟</h4><div className="check-answers">{names.map((name,i)=><button key={name} aria-pressed={guess===i} onClick={()=>setGuess(i)}>{name}</button>)}</div>{guess!==null&&<p role="status">{guess===0?'بالضبط! علامة قف عندها ثمانية الأضلاع.':'رجع شوف الحواف ديال علامة قف وعدّهم. جرّب مرة أخرى.'}</p>}<small>تذكّر بصري، بلا تنقيط.</small></div>}</section>;
}

export function StoppingLab(){
 const [speed,setSpeed]=useState(60),[reaction,setReaction]=useState(1),[deceleration,setDeceleration]=useState(6),[phase,setPhase]=useState(0),[guess,setGuess]=useState(null);
 const d=stoppingDistances(speed,reaction,deceleration),scale=100/320;
 const phases=['رد الفعل','الفرملة','الوقوف'];const at=[d.reaction,d.total,d.total][phase];
 return <section className="stopping-lab"><div className="stage-eyebrow"><span>مختبر المسافات</span><span>لاحظ الفرق</span></div><h3>قبل ما توقف… كاينين جوج مراحل</h3><p className="lab-lead">الطوموبيل كتدوز مسافة قبل بداية الفرملة، ومن بعدها كتحتاج مسافة باش توقف.</p><div className="phase-picker" aria-label="مراحل الوقوف">{phases.map((p,i)=><button key={p} aria-pressed={phase===i} onClick={()=>setPhase(i)}><b>0{i+1}</b>{p}</button>)}</div>
 <div className="stopping-road" dir="ltr" aria-hidden="true"><div className="road-ruler">0 m <span>320 m</span></div><div className="reaction-strip" style={{width:d.reaction*scale+'%'}}/><div className="braking-strip" style={{left:d.reaction*scale+'%',width:d.braking*scale+'%'}}/><span className={'model-car phase-'+phase} style={{left:Math.min(94,at*scale)+'%'}}><svg viewBox="0 0 70 40" aria-hidden="true"><path d="M4 20 16 17 25 5H46L56 17 66 21V32H4Z" fill="#29abe2" stroke="#e9fbff" strokeWidth="2"/><path d="M27 9H44L51 17H21Z" fill="#173e50"/><circle cx="18" cy="32" r="7" fill="#173e50"/><circle cx="54" cy="32" r="7" fill="#173e50"/><circle cx="18" cy="32" r="3" fill="white"/><circle cx="54" cy="32" r="3" fill="white"/></svg></span></div>
 <p className="phase-explanation" aria-live="polite">{['شفت الموقف، ولكن الفرملة ما بداتش بعد. المسافة الزرقاء كتدوز فوقت رد الفعل.','دابا بدات الفرملة. المسافة الذهبية كتزاد على المسافة اللي دازت قبلها.','الوقوف كيجمع المرحلتين: مسافة رد الفعل + مسافة الفرملة.'][phase]}</p>
 <div className="distance-results" aria-live="polite"><div><small>رد الفعل</small><b>{d.reaction.toFixed(1)} <em>م</em></b></div><span>+</span><div><small>الفرملة</small><b>{d.braking.toFixed(1)} <em>م</em></b></div><span>=</span><div><small>الوقوف</small><b>{d.total.toFixed(1)} <em>م</em></b></div></div>
 <p className="model-caption">نموذج توضيحي بتباطؤ ثابت؛ الأرقام مقربة. ماشي مسافة مضمونة فالطريق.</p><div className="lab-sliders"><label>السرعة <strong>{speed} كلم/س</strong><input type="range" min="20" max="120" step="10" value={speed} onChange={e=>setSpeed(+e.target.value)}/></label><label>وقت رد الفعل <strong>{reaction} ثانية</strong><input type="range" min="0.5" max="3" step="0.5" value={reaction} onChange={e=>setReaction(+e.target.value)}/></label><label>التباطؤ المفترض <strong>{deceleration} م/ث²</strong><input type="range" min="3" max="8" step="1" value={deceleration} onChange={e=>setDeceleration(+e.target.value)}/></label></div>
 <details className="model-notes"><summary>كيفاش تحسبات هاد التجربة؟</summary><p>هاد نموذج حسابي مبسط بتباطؤ ثابت. رد الفعل = السرعة بالمتر/الثانية × الوقت. الفرملة = مربع السرعة بالمتر/الثانية ÷ (2 × التباطؤ). الأرقام توضيحية، ماشي ضمان لمسافة الوقوف فالطريق؛ الحالة ديال العجلات والطريق والفرانات كتأثر عليها.</p><p>السرعة هنا متغير للتجربة، ماشي سرعة مسموحة أو توصية بالسير.</p><a href="https://modules.securite-routiere.gouv.fr/module_distance_arret.html" target="_blank" rel="noreferrer">مرجع توضيحي للمراحل</a></details>
 <div className="concept-check"><h4>إيلا تزاد وقت رد الفعل، وبقاو باقي المعطيات كيفما هما؟</h4><div className="check-answers">{['كتزاد المسافة قبل الفرملة','كتبقى المسافة كيفما هي'].map((t,i)=><button key={t} aria-pressed={guess===i} onClick={()=>setGuess(i)}>{t}</button>)}</div>{guess!==null&&<p role="status">{guess===0?'صحيح! جرّب تزاد الوقت بالسهم وشوف الجزء الأزرق كيكبر.':'جرّب تزاد وقت رد الفعل وشوف شنو كيوقع للجزء الأزرق.'}</p>}<small>هاد المحاولة للتعلم، بلا تنقيط.</small></div>
 </section>;
}
