import React, { useEffect, useRef, useState } from 'react';
import './journey.css';
import {LessonMedia,PriorityScene} from './LessonStage';
import {SignSteps,StoppingLab} from './ConceptScenes';

const icons=['priority','speed','overtaking','parking','lighting','safety','license','mechanics','driver-state','highway'];
const clean=t=>(t||'').replace(/\([^)]*[A-Za-z][^)]*\)/g,'').trim();
export const JourneyIcon=({number=1})=><img src={'/visual/icons/icon-'+icons[(number-1)%10]+'.svg'} alt="" width="32" height="32"/>;

function Companion({small=false}){
 return <div className={'companion '+(small?'small':'')} aria-hidden="true"><div className="companion-antenna"/><div className="companion-face"><span/><span/><i/></div><div className="companion-wheel">✦</div></div>;
}

export function JourneyMap({items,progress,onOpen,user}){
 const done=l=>progress.filter(p=>p.revision_id===l.revision_id&&p.completed).length;
 const complete=items.filter(l=>done(l)===Number(l.section_count)).length;
 const read=items.reduce((n,l)=>n+done(l),0),total=items.reduce((n,l)=>n+Number(l.section_count),0);
 const next=items.find(l=>done(l)<Number(l.section_count))||items[0];
 return <div className="journey-home"><section className="journey-hero"><div className="journey-welcome"><span className="journey-kicker">رحلتك مع PerminIA</span><h1>خطوات صغيرة،<br/><em>ثقة أكبر.</em></h1><p>ما خاصكش تحفظ كلشي دقة وحدة.<br/>فكرة صغيرة، تجربة، وخطوة لقدّام.</p>{next&&<button className="play-button" onClick={()=>onOpen(next.slug)}>{read?'متابعة الرحلة':'ابدأ الرحلة'}<span>←</span></button>}</div><div className="journey-guide"><div className="guide-bubble">واجدين لجولة جديدة؟ <span>✦</span></div><Companion/><div className="guide-shadow"/></div><div className="hero-landscape" aria-hidden="true"><i/><i/><i/></div></section>
 <div className="journey-dashboard"><div><b>{complete}<span> / {items.length}</span></b><small>دروس كملتي قرايتهم</small></div><div><b>{read}<span> / {total}</span></b><small>خطوات القراءة المحفوظة</small></div><div className="journey-meter"><span>{user?'التقدم ديالك، على خاطرك':'اكتشف الرحلة وجرّب'}</span><progress aria-label="تقدم القراءة" value={read} max={total||1}/><small>{user?'كل خطوة صغيرة كتفرق.':'دخل للحساب باش تبقى خطواتك محفوظة.'}</small></div></div>
 <div className="journey-columns"><section className="learning-trail"><div className="trail-heading"><span>{items.length} دروس</span><h2>خريطة التعلم</h2><p>بدا من هنا، أو اختار المحور اللي محتاج.</p></div><div className="trail-line" aria-hidden="true"/>{items.map((l,index)=>{const count=done(l),finished=count===Number(l.section_count),current=l.id===next?.id;return <article key={l.id} className={'trail-stop tone-'+index%3+(current?' suggested':'')+(finished?' finished':'')}><div className="trail-node" aria-hidden="true">{finished?'✓':String(index+1).padStart(2,'0')}</div><button className="trail-card" onClick={()=>onOpen(l.slug)}><span className="trail-icon"><JourneyIcon number={l.position}/></span><span className="trail-copy">{current&&<small className="trail-suggestion">الخطوة المقترحة</small>}<strong>{clean(l.title_ar)}</strong><span>{l.summary_darija}</span><span className="trail-dots" aria-label={`${count} من ${l.section_count} خطوات مقروءة`}>{Array.from({length:Number(l.section_count)},(_,i)=><i key={i} className={i<count?'read':''}/>)}<small>{l.section_count} خطوات</small></span></span><span className="trail-arrow">←</span></button></article>;})}</section>
 <aside className="journey-side"><div className="discovery-card"><span className="journey-kicker">كيفاش غادي نتعلمو؟</span><h2>طريق واضح،<br/>خطوة بخطوة.</h2><ol><li><b>01</b><span>شوف الفكرة</span></li><li><b>02</b><span>جرّب وكتاشف</span></li><li><b>03</b><span>ثبت القراءة وكمل</span></li></ol><img src="/visual/previews/anim-car-driving-preview.svg" alt=""/></div><div className="encouragement"><Companion small/><p>ما كاين لا سباق لا ضغط. رجع لأي خطوة فوقاش بغيتي.</p></div><p className="journey-fineprint">تقدم القراءة ماشي نقطة امتحان، وما كيعنيش بوحدو أنك أتقنت الدرس.</p></aside></div>
 </div>;
}

function DistanceLab(){
 const [speed,setSpeed]=useState(60),[seconds,setSeconds]=useState(1);
 const distance=speed/3.6*seconds;
 return <section className="distance-lab"><div className="lab-heading"><span>جرّب بيدك</span><h3>اكتشف مسافة رد الفعل</h3><p>بدّل السرعة ووقت رد الفعل، وشوف المسافة اللي كتدوز قبل الفرملة.</p></div><div className="lab-road" aria-hidden="true"><div className="distance-line" style={{width:(distance/100*75+10)+'%'}}/><img style={{left:Math.min(78,distance/100*75+5)+'%'}} src="/visual/previews/anim-car-driving-preview.svg" alt=""/></div><output aria-live="polite"><b>{distance.toFixed(1)}</b> متر قبل الفرملة</output><label>السرعة <strong>{speed} كلم/س</strong><input type="range" min="20" max="120" step="10" value={speed} onChange={e=>setSpeed(Number(e.target.value))}/></label><label>وقت رد الفعل <strong>{seconds} ثانية</strong><input type="range" min="0.5" max="3" step="0.5" value={seconds} onChange={e=>setSeconds(Number(e.target.value))}/></label><small>تجربة حسابية: المسافة = السرعة ÷ 3.6 × الوقت. ماشي مسافة الوقوف، وماشي توصية بسرعة السير.</small></section>;
}

function MemoryCards({chunks}){
 const [revealed,setRevealed]=useState(false);
 return <div className="memory-card"><span className="memory-star">✦</span><h3>لحظة للتذكّر</h3><p>حاول تشرح الفكرة بكلامك قبل ما ترجع تشوفها. ما كاين حتى تنقيط هنا.</p><button className="secondary" aria-expanded={revealed} onClick={()=>setRevealed(v=>!v)}>{revealed?'إخفاء التذكير':'كشف التذكير'}</button>{revealed&&<p className="memory-answer">{chunks[0]}</p>}</div>;
}

function CarDiscovery(){
 const [part,setPart]=useState('mirrors');
 const parts={mirrors:['المرايا','كتعاونك تشوف شنو واقع وراك وحذاك. ولكن الصورة اللي فيها ما كتغطيش كلشي.'],tires:['العجلات','هي نقطة الاتصال بين الطوموبيل والطريق. الفحص ديالها كيهم الضغط والحالة ديال النقوش.'],lights:['الأضواء','كتعاونك تشوف الطريق، وكتعاون الآخرين يشوفوك ويفهمو الإشارات ديالك.']};
 return <section className="car-discovery"><span className="journey-kicker">كتاشف الطوموبيل</span><h3>اكتشف أجزاء السيارة</h3><svg viewBox="0 0 400 210" role="img" aria-label="رسم مبسط لسيارة مع المرايا والأضواء والعجلات"><ellipse cx="200" cy="175" rx="170" ry="15" fill="#c8e4ed"/><path d="M40 135 70 115 110 55Q120 43 145 43H250Q265 43 279 65L315 115 355 128V165H40Z" fill="#29abe2" stroke="#0a5d7a" strokeWidth="5"/><path d="M115 65H180V110H90Z M195 65H250L282 110H195Z" fill="#d8f6ff" stroke="#0a5d7a" strokeWidth="4"/><circle cx="100" cy="165" r="28" fill={part==='tires'?'#f5a623':'#153f50'}/><circle cx="298" cy="165" r="28" fill={part==='tires'?'#f5a623':'#153f50'}/><circle cx="100" cy="165" r="12" fill="#edf8fc"/><circle cx="298" cy="165" r="12" fill="#edf8fc"/><rect x="295" y="103" width="24" height="16" rx="7" fill={part==='mirrors'?'#f5a623':'#0a5d7a'}/><rect x="330" y="133" width="28" height="15" rx="6" fill={part==='lights'?'#f5a623':'#eafaff'}/>{part==='lights'&&<path d="M362 129 397 115V165L362 151Z" fill="#f5a623" opacity=".4"/>}</svg><div className="discovery-options">{Object.entries(parts).map(([id,[label]])=><button key={id} aria-pressed={part===id} onClick={()=>setPart(id)}>{label}</button>)}</div><p aria-live="polite">{parts[part][1]}</p></section>;
}

function Celebration({onClose,onNext,last}){
 const ref=useRef(null);
 useEffect(()=>{const previous=document.activeElement;ref.current.showModal();return()=>previous?.focus();},[]);
 return <dialog ref={ref} className="journey-celebration" aria-label="تم حفظ القراءة" onCancel={e=>{e.preventDefault();onClose();}}><div className="confetti" aria-hidden="true">{Array.from({length:12},(_,i)=><i key={i} style={{'--n':i}}/>)}</div><button className="celebration-close" aria-label="إغلاق" onClick={onClose}>×</button><img src="/visual/achievements/badge-first-step.svg" alt=""/><span className="journey-kicker">خطوة محفوظة</span><h2>خطوة جديدة في رحلتك!</h2><p>القراءة ديالك تحفظات فالحساب.<br/>دابا خد نفس، وكمل على خاطرك.</p><button className="play-button" onClick={onNext}>{last?'العودة إلى الخريطة':'الفقرة الموالية'} <span>←</span></button><button className="quiet-button" onClick={onClose}>البقاء هنا</button></dialog>;
}

export function FocusLesson({lesson,sections,section,state,user,busy,onSave,onNavigate,onExit}){
 const [step,setStep]=useState(0),[celebrate,setCelebrate]=useState(false),[full,setFull]=useState(false);
 const chunks=(section.body_darija.match(/[^\n]+/g)||[]).flatMap(line=>line.length>320?line.split(/(?<=[.!؟])\s+/u):[line]).filter(x=>x.trim());
 const last=step===chunks.length,position=section.position;
 const synthetic=lesson.slug.startsWith('showcase-');
 async function finish(){if(await onSave({completed:true}))setCelebrate(true);}
 return <div className="focus-experience"><header className="focus-header"><button className="quiet-button" onClick={onExit}>→ الخريطة</button><div><span>الفقرة {position} من {sections.length}</span><progress aria-label="خطوات الفقرة" value={step+1} max={chunks.length+1}/></div><button className="bookmark-button" disabled={busy} aria-pressed={!!state.bookmarked} onClick={()=>onSave({bookmarked:!state.bookmarked})}>{state.bookmarked?'★ في المفضلة':'☆ إضافة للمفضلة'}</button></header><div className="focus-layout"><div className="focus-main"><div className="focus-title"><span className="trail-icon"><JourneyIcon number={lesson.position}/></span><div><span className="journey-kicker">{clean(lesson.title_ar)}</span><h2>{clean(section.title_ar)}</h2></div></div>{lesson.slug==='asba9ia-wa-molta9ayat'&&position===1?<PriorityScene/>:lesson.slug==='asba9ia-wa-molta9ayat'&&position===2?<SignSteps step={step} review={last} onStep={setStep}/>:!synthetic&&lesson.position===2&&position===4?<StoppingLab/>:<LessonMedia media={section.media||[]}/>}<div className="focus-step" key={step} aria-live="polite">{!last?<><span className="step-counter">فكرة {step+1} / {chunks.length}</span><p className="bite-text">{chunks[step]}</p><div className="bite-accent" aria-hidden="true">✦</div></>:<MemoryCards chunks={chunks}/>}</div>{last&&!synthetic&&lesson.position===2&&position!==4&&<DistanceLab/>}{last&&!synthetic&&lesson.position===8&&<CarDiscovery/>}<div className="focus-controls"><button className="secondary" disabled={step===0||busy} onClick={()=>setStep(n=>n-1)}>السابق</button>{last?<button className="play-button" disabled={busy} onClick={finish}>{busy?'جارٍ الحفظ…':user?'حفظ القراءة':'الدخول لحفظ القراءة'}<span>✓</span></button>:<button className="play-button" onClick={()=>setStep(n=>n+1)}>متابعة<span>←</span></button>}</div><div className="focus-steps" aria-label="التقدم داخل الفقرة">{chunks.map((_,i)=><span key={i} className={i<=step?'seen':''}/>)}</div><button className="quiet-button full-text-toggle" aria-expanded={full} onClick={()=>setFull(v=>!v)}>{full?'إخفاء النص الكامل':'عرض النص الكامل'}</button>{full&&<p className="full-lesson-text">{section.body_darija}</p>}</div><aside className="focus-side"><div className="coach-note"><Companion small/><p>خد وقتك مع كل فكرة. التكرار كيساعدها تبقى فالبال.</p></div><nav aria-label="فقرات الدرس">{sections.map(s=><button disabled={busy} key={s.position} className={position===s.position?'active':''} onClick={()=>onNavigate(s.position)}><b>{s.position}</b>{clean(s.title_ar)}</button>)}</nav><details><summary>الأخطاء الشائعة والنصيحة</summary><p>{lesson.common_mistakes_darija}</p><p>{lesson.coach_tip}</p></details></aside></div>{celebrate&&<Celebration last={position===sections.length} onClose={()=>setCelebrate(false)} onNext={()=>{setCelebrate(false);position===sections.length?onExit():onNavigate(position+1);}}/>}</div>;
}
