import {useRouteState,readRoute} from './navigation';
import {MarkReview} from './ReviewNotebook';
import { JourneyMap, FocusLesson } from './LearningJourney';
import React, { useEffect, useState } from 'react';

const heading=text=>(text||'').replace(/\([^)]*[A-Za-z][^)]*\)/g,'').trim();
const base='/api/v1/student/preview';
async function request(path,body){
 const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),15000);
 try {const r=await fetch(base+path,{signal:controller.signal,credentials:'same-origin',method:body?'PUT':'GET',headers:body?{'Content-Type':'application/json','X-Sya9a-Request':'student'}:{},body:body?JSON.stringify(body):undefined});
 if(!r.ok)throw new Error(r.status===401?'دخل للحساب باش تحفظ القراءة ديالك.':'ما قدرناش نكملو الطلب. عاود جرّب.');
 return await r.json();} catch(e){if(e.name==='AbortError'||e instanceof TypeError)throw new Error('الاتصال تعطل. عاود جرّب.');throw e;} finally{clearTimeout(timeout);}
}
export default function Lessons({user,onLogin,initialSlug=null,initialPosition=null}){
 const [items,setItems]=useState(null),[slug,setSlug]=useRouteState('lesson',initialSlug),[detail,setDetail]=useState(null),[progress,setProgress]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[position,setPosition]=useRouteState('position',initialPosition||1),[tab,setTab]=useState('lessons'),[signs,setSigns]=useState(null),[query,setQuery]=useState(''),[group,setGroup]=useState(''),[limit,setLimit]=useState(24),[retry,setRetry]=useState(0),[zoom,setZoom]=useState(null);
 useEffect(()=>{let current=true;setError('');Promise.all([request('/lessons'),user?request('/lesson-progress'):Promise.resolve({items:[]})]).then(([l,p])=>{if(current){setItems(l.items);setProgress(p.items);}}).catch(e=>current&&setError(e.message));return()=>{current=false;};},[user,retry]);
 useEffect(()=>{if(!slug)return;let current=true;setDetail(null);setError('');Promise.all([request('/lessons/'+slug),user?request('/lesson-progress'):Promise.resolve({items:[]})]).then(([d,p])=>{if(current){setDetail(d);setProgress(p.items);const previous=p.items.filter(x=>x.revision_id===d.lesson.revision_id).at(-1);const target=readRoute('position',null)||previous?.section_position;setPosition(d.sections.some(s=>s.position===target)?target:(d.sections[0]?.position||1));}}).catch(e=>current&&setError(e.message));return()=>{current=false;};},[slug,retry,user?.membership_id,initialSlug,initialPosition]);
 useEffect(()=>{if(tab!=='signs')return;let current=true;request('/signs').then(d=>current&&setSigns(d.items)).catch(e=>current&&setError(e.message));return()=>{current=false;};},[tab,retry]);
 async function save(values){if(!user){onLogin();return false;}setBusy(true);setError('');try{const revision_id=detail.lesson.revision_id;await request('/lesson-progress/'+revision_id,{section_position:position,...values});setProgress(old=>{const previous=old.find(p=>p.revision_id===revision_id&&p.section_position===position)||{};return [...old.filter(p=>!(p.revision_id===revision_id&&p.section_position===position)),{...previous,revision_id,section_position:position,...values}];});return true;}catch(e){setError(e.message);return false;}finally{setBusy(false);}}
 const section=detail?.sections.find(s=>s.position===position),state=progress.find(p=>p.revision_id===detail?.lesson.revision_id&&p.section_position===position)||{};
 const filtered=(signs||[]).filter(s=>(!group||s.section_name===group)&&(!query||[s.title_ar,s.meaning_darija].join(' ').includes(query.trim())));
 return <section className="lessons-page"><div className="journey-topline"><span>فضاء الاكتشاف</span><span>تعلّم • جرّب • تقدّم</span></div>
 <details className="preview-disclosure"><summary>محتوى تجريبي قيد المراجعة</summary><p>هاد الدروس باقي كنراجعوها، وبعض المعلومات فيها خاصها التصحيح. هادي تجربة للتعلم، وماشي مرجع قانوني معتمد.</p></details>
 {(!slug||tab==='signs')&&<div className="lesson-tabs"><button className={tab==='lessons'?'primary':'secondary'} onClick={()=>{setTab('lessons');setSlug(null);}}>الدروس</button><button className={tab==='signs'?'primary':'secondary'} onClick={()=>setTab('signs')}>علامات التشوير</button></div>}
 {error&&<div className="form-error" role="alert">{error} <button className="secondary" onClick={()=>setRetry(n=>n+1)}>إعادة المحاولة</button></div>}
 {tab==='lessons'&&!slug&&items&&<JourneyMap items={items} progress={progress} user={user} onOpen={value=>{setPosition(null);setSlug(value);window.scrollTo({top:0});}}/>}
 {tab==='lessons'&&slug&&detail&&section&&<FocusLesson key={'focus:'+detail.lesson.revision_id+':'+position} lesson={detail.lesson} sections={detail.sections} section={section} state={state} user={user} busy={busy} onSave={save} onExit={()=>{setSlug(null);window.scrollTo({top:0});}} onNavigate={async value=>{setPosition(value);window.scrollTo({top:0,behavior:'instant'});if(user){setBusy(true);try{await request('/lesson-progress/'+detail.lesson.revision_id,{section_position:value});setProgress(old=>{const previous=old.find(x=>x.revision_id===detail.lesson.revision_id&&x.section_position===value)||{};return [...old.filter(x=>!(x.revision_id===detail.lesson.revision_id&&x.section_position===value)),{...previous,revision_id:detail.lesson.revision_id,section_position:value}];});}catch(e){setError(e.message);}finally{setBusy(false);}}}}/>}
 {tab==='lessons'&&detail&&slug&&user&&<MarkReview key={'review:'+detail.lesson.revision_id+':'+position} kind="lesson" revisionId={detail.lesson.revision_id} position={position}/>}
 {tab==='signs'&&<><div className="sign-filters"><label>البحث<input value={query} onChange={e=>{setQuery(e.target.value);setLimit(24);}} placeholder="قلب على شي علامة…"/></label><label>الصنف<select value={group} onChange={e=>{setGroup(e.target.value);setLimit(24);}}><option value="">جميع الأصناف</option>{[...new Set((signs||[]).map(s=>s.section_name))].map(g=><option key={g}>{g}</option>)}</select></label></div><div className="sign-grid">{filtered.slice(0,limit).map(s=><article className="sign-card" key={s.id}><button className="sign-image" onClick={()=>setZoom(s)} aria-label={'تكبير '+s.title_ar}><img loading="lazy" src={base+'/sign-media/'+s.asset_id} alt={s.title_ar}/></button><h2>{s.title_ar}</h2><p>{s.meaning_darija}</p></article>)}</div>{signs&&!filtered.length&&<p className="load-state">ما لقينا حتى علامة بهاد البحث.</p>}{filtered.length>limit&&<button className="secondary" onClick={()=>setLimit(n=>n+24)}>عرض المزيد</button>}</>}
 {((tab==='lessons'&&(!items||(slug&&!detail)))||(tab==='signs'&&!signs))&&!error&&<p className="load-state">كنوجدو المحتوى…</p>}
 {zoom&&<dialog className="sign-zoom" ref={node=>{if(node&&!node.open)node.showModal();}} onCancel={()=>setZoom(null)} aria-label={zoom.title_ar}><button className="secondary" onClick={()=>setZoom(null)}>إغلاق</button><img src={base+'/sign-media/'+zoom.asset_id} alt={zoom.title_ar}/><h2>{zoom.title_ar}</h2></dialog>}
 </section>;
}

