import React,{useEffect,useState} from 'react';
import {journeyRequest} from './journey-api';
import './notebook.css';
const reasons={unclear:'ما فهمتش',hesitated:'ترددت',ask:'بغيت نسول عليها'};
const clean=s=>(s||'').replace(/\([^)]*[A-Za-z][^)]*\)/g,'').trim();
export function MarkReview({kind,revisionId,position}){
 const [reason,setReason]=useState('unclear'),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function save(e){e.preventDefault();setBusy(true);setMessage('');try{await journeyRequest('/notebook',{kind,revision_id:revisionId,section_position:position??null,reason,note});setMessage('تحفظات فدفتر المراجعة. إلا كانت مسالية، تقدر تعاود تفتحها من الدفتر.');}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 return <details className="review-mark"><summary>☆ أضف إلى دفتر المراجعة</summary><form onSubmit={save}><label>السبب<select value={reason} onChange={e=>setReason(e.target.value)}>{Object.entries(reasons).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>ملاحظة اختيارية<textarea maxLength={600} value={note} onChange={e=>setNote(e.target.value)} placeholder="شنو اللي بغيتي ترجع ليه؟"/></label><button className="secondary" disabled={busy}>{busy?'جارٍ الحفظ…':'حفظ في الدفتر'}</button><p role="status">{message}</p></form></details>;
}
export function NotebookPreview({onNavigate}){
 const [data,setData]=useState(null);
 useEffect(()=>{let alive=true;journeyRequest('/notebook').then(d=>alive&&setData(d)).catch(()=>{});return()=>{alive=false;};},[]);
 return <div className="notebook-preview"><span>↻</span><div><b>وقت المراجعة</b><p>{data?`${data.due_count} عناصر وصل موعدها. اختار فكرة ورجع ليها بشوية.`:'جمع الأسئلة والفقرات اللي محتاج ترجع ليها.'}</p></div><button className="secondary" onClick={()=>onNavigate('notebook')}>فتح الدفتر</button></div>;
}
export default function ReviewNotebook({user,onLogin,onLesson,onExplore}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[retry,setRetry]=useState(0),[filter,setFilter]=useState('due');
 useEffect(()=>{if(!user)return;let alive=true;setError('');journeyRequest('/notebook').then(d=>alive&&setData(d)).catch(e=>alive&&setError(e.message));return()=>{alive=false;};},[user?.membership_id,retry]);
 async function act(item,action,days=1){setBusy(true);setError('');try{await journeyRequest('/notebook/'+item.id,{expected_version:item.version,action,days},'PATCH');setRetry(x=>x+1);}catch(e){setError(e.message);}finally{setBusy(false);}}
 if(!user)return <section className="completion"><h1>دفتر المراجعة ديالك</h1><p>دخل للحساب باش تجمع الحوايج اللي محتاج ترجع ليها.</p><button className="primary" onClick={onLogin}>تسجيل الدخول</button></section>;
 const items=(data?.items||[]).filter(i=>filter==='all'||filter==='due'&&i.due||filter==='later'&&i.state==='open'&&!i.due||filter==='done'&&i.state==='done');
 return <section className="notebook-page"><header className="notebook-hero"><span className="eyebrow">فهم الفكرة، ورجع ليها</span><h1>دفتر المراجعة</h1><p>ما فهمتيش شي نقطة؟ خليها هنا. راجعها على خاطرك وقرر فوقاش ترجع ليها.</p></header>
 {error&&<p role="alert" className="form-error">{error}<button onClick={()=>setRetry(x=>x+1)}>تحديث</button></p>}
 {!data?<p role="status">كنوجدو الدفتر…</p>:<><details className="notebook-week"><summary>مجهود آخر 7 أيام</summary><div className="notebook-stats">{[[data.week.active_days,'أيام النشاط'],[data.week.sections,'فقرات مكتملة'],[data.week.runs,'جولات مكتملة'],[data.week.reviews,'مراجعات صرّحت بها']].map(([v,l])=><div key={l}><strong>{v}</strong><span>{l}</span></div>)}</div><div className="notebook-days">{data.week.days.map(d=><span key={d.day} className={d.active?'active':''} title={d.day}>{new Date(d.day+'T12:00:00').toLocaleDateString('ar-MA',{weekday:'short'})}<b>{d.active?'✓':'·'}</b></span>)}</div><div className="notebook-badges">{data.week.badges.map(b=><span key={b}>✦ {b}</span>)}</div><p className="sd-note">شارات مجهود هاد الأسبوع، ماشي قياس الإتقان. الأرقام ما فيهاش نقط المحاكاة.</p></details>
 <nav className="sd-tabs" aria-label="تصفية دفتر المراجعة">{[['due','حان وقتها'],['later','لاحقاً'],['done','مكتملة'],['all','الكل']].map(([id,l])=><button key={id} className={filter===id?'active':''} aria-pressed={filter===id} onClick={()=>setFilter(id)}>{l}</button>)}</nav>
 {!items.length&&<div className="notebook-empty"><span>☆</span><h2>ما كاين حتى عنصر فهاد اللائحة</h2><p>من داخل درس أو تدريب محفوظ، ضغط على «أضف إلى دفتر المراجعة».</p><button className="primary" onClick={onExplore}>استكشاف الدروس</button></div>}
 <div className="notebook-items">{items.map(item=><article key={item.id} className="notebook-item"><div className="notebook-meta"><span>{item.kind==='lesson'?'فقرة درس':'سؤال تدريب'} · {reasons[item.reason]}</span><span>{item.due_on}</span></div><h2>{clean(item.section_title)||item.prompt||'سؤال بالصورة'}</h2>{item.lesson_title&&<p>{clean(item.lesson_title)}</p>}{item.note&&<blockquote>{item.note}</blockquote>}
 {!item.available?<p>نسخة هاد المحتوى ما بقاتش متاحة. الملاحظة ديالك باقية محفوظة.</p>:item.kind==='lesson'?<button className="primary" onClick={()=>onLesson(item.slug,item.section_position)}>فتح الفقرة ←</button>:<details><summary>عرض السؤال والاختيارات</summary>{item.image_url&&<img src={item.image_url} alt="صورة السؤال للمراجعة" loading="lazy"/>}<ul>{(item.choices||[]).map(c=><li key={c.id}>{c.number}. {c.text}</li>)}</ul><p className="sd-note">هاد العرض للمراجعة الحرة، بلا مؤقت أو تصحيح آلي.</p></details>}
 <div className="notebook-actions">{item.state==='done'?<button disabled={busy} onClick={()=>act(item,'reopen')}>إعادة الفتح</button>:<><button disabled={busy||!item.available} onClick={()=>act(item,'review',1)}>راجعتها · نراجعها غداً</button><details><summary>خيارات الموعد والإنهاء</summary><button disabled={busy||!item.available} onClick={()=>act(item,'review',3)}>راجعتها · بعد 3 أيام</button><button disabled={busy||!item.available} onClick={()=>act(item,'review',7)}>راجعتها · بعد أسبوع</button><button disabled={busy} onClick={()=>act(item,'snooze',1)}>تأجيل للغد</button><button disabled={busy||!item.available} onClick={()=>act(item,'close')}>راجعتها وانتهيت</button></details></>}</div></article>)}</div><p className="sd-note">نفس العنصر كيتحسب مرة واحدة فاليوم. التأجيل بوحدو ما كيتحسبش مراجعة.</p></>}
 </section>;
}
