import React,{useEffect,useState} from 'react';
import {journeyRequest} from './journey-api';
import './student-dashboard.css';
import DailyPlan from './DailyPlan';

const dateLabel=value=>value?new Date(value).toLocaleDateString('ar-MA',{day:'numeric',month:'short'}):'ما تحددش';
function RoadArt(){return <svg className="sd-road" viewBox="0 0 360 230" aria-hidden="true"><circle cx="280" cy="62" r="43" fill="#f5a623"/><path d="M-20 205Q120 205 120 118T380 85" fill="none" stroke="#207f97" strokeWidth="58"/><path d="M-20 205Q120 205 120 118T380 85" fill="none" stroke="#a4dfed" strokeWidth="3" strokeDasharray="10 12"/><g className="sd-car" transform="translate(210 58)"><rect width="62" height="33" rx="12" fill="#fff"/><rect x="20" y="5" width="25" height="23" rx="6" fill="#29abe2"/><path d="M15 0v6m0 23v5m34-34v6m0 23v5" stroke="#073e51" strokeWidth="7"/></g><path d="M63 113V49m0 0q28-14 45 0v29q-22-15-45 0" fill="#f5a623" stroke="#f5a623" strokeWidth="4"/><circle cx="313" cy="191" r="5" fill="#72d9e1"/><path d="M38 158h16m-8-8v16" stroke="#72d9e1" strokeWidth="3"/></svg>}
function Trend({days}){
 const points=days.map((d,i)=>d.score===null?null:{x:15+i*570/27,y:150-d.score*1.25,...d}).filter(Boolean);
 return <><svg className="sd-chart" viewBox="0 0 600 175" role="img" aria-label="تطور المعدل التجريبي خلال 28 يوم، التفاصيل متاحة أسفل الرسم"><defs><linearGradient id="sd-fill" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#29abe2" stopOpacity=".24"/><stop offset="1" stopColor="#29abe2" stopOpacity="0"/></linearGradient></defs>{[25,50,75,100].map(n=><g key={n}><path d={`M15 ${150-n*1.25}H585`} stroke="#e7eff3" strokeDasharray="4 5"/><text x="3" y={145-n*1.25} fill="#758b97" fontSize="10">{n}</text></g>)}{points.length>1&&<><path d={`M${points[0].x} 155 L${points.map(p=>`${p.x} ${p.y}`).join(' L')} L${points.at(-1).x} 155Z`} fill="url(#sd-fill)"/><polyline points={points.map(p=>`${p.x},${p.y}`).join(' ')} fill="none" stroke="#0a789c" strokeWidth="3" strokeLinejoin="round"/></>}{points.map(p=><circle key={p.date} cx={p.x} cy={p.y} r="4" fill="#f5a623" stroke="white" strokeWidth="2"><title>{dateLabel(p.date)}: {p.score}%</title></circle>)}</svg><div className="sd-axis"><span>{dateLabel(days[0]?.date)}</span><span>{dateLabel(days.at(-1)?.date)}</span></div>{!points.length&&<p>ملي تتوفر نتائج مصححة، غادي يبان التطور هنا.</p>}<details className="sd-details"><summary>عرض بيانات الرسم</summary><div className="sd-table-wrap"><table><thead><tr><th>التاريخ</th><th>المعدل التجريبي</th></tr></thead><tbody>{points.map(p=><tr key={p.date}><td>{dateLabel(p.date)}</td><td>{p.score}%</td></tr>)}</tbody></table></div></details></>;
}
export default function StudentDashboard({user,onLogin,onNavigate}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[retry,setRetry]=useState(0),[tab,setTab]=useState('overview');
 const [exam,setExam]=useState(''),[minutes,setMinutes]=useState(20),[saving,setSaving]=useState(false),[saved,setSaved]=useState('');
 const [coach,setCoach]=useState(null),[coachBusy,setCoachBusy]=useState(false),[coachError,setCoachError]=useState('');
 useEffect(()=>{if(!user)return;let alive=true;setError('');setData(null);journeyRequest().then(d=>{if(alive){setData(d);setExam(d.profile.exam_on||'');setMinutes(d.profile.daily_minutes);}}).catch(e=>alive&&setError(e.message));return()=>{alive=false;};},[user?.membership_id,retry]);
 async function save(e){e.preventDefault();setSaving(true);setSaved('');try{await journeyRequest('/goal',{exam_on:exam||null,daily_minutes:Number(minutes)},'PUT');setSaved('تحفظ الهدف ديالك.');setRetry(n=>n+1);}catch(e){setSaved(e.message);}finally{setSaving(false);}}
 async function ask(intent){setCoachBusy(true);setCoachError('');try{setCoach(await journeyRequest('/coach',{intent}));}catch(e){setCoachError(e.message);}finally{setCoachBusy(false);}}
 if(!user)return <section className="sd-welcome"><span className="eyebrow">رحلتك، على قياسك</span><h1>كل نهار، أقرب للرخصة.</h1><p>دخل للحساب ديالك باش تشوف التقدم، توجد برنامج المراجعة وتلقى التوجيه على حساب التدريب ديالك.</p><button className="primary" onClick={onLogin}>تسجيل الدخول</button><button className="secondary" onClick={()=>onNavigate('lessons')}>استكشاف الدروس</button><div className="sd-welcome-grid">{['مسار حتى للامتحان','مراجعة على حساب المستوى','مرافق للتعلم بالدارجة'].map((t,i)=><article key={t}><b>0{i+1}</b><h3>{t}</h3></article>)}</div></section>;
 if(error)return <div className="load-state" role="alert"><p>{error}</p><button className="primary" onClick={()=>setRetry(n=>n+1)}>إعادة المحاولة</button></div>;
 if(!data)return <div className="load-state" role="status">كنوجدو الرحلة ديالك…</div>;
 const progress=data.total_sections?Math.round(data.completed_sections/data.total_sections*100):0;
 return <div className="student-dashboard">
  {data.is_demo&&<div className="sd-demo"><span>◈ محاكاة تجريبية</span><p>بروفايل «{data.profile.persona}». نقط الأداء مولّدة باش نختبرو التتبع؛ القراءة والجولات الجديدة كيتسجلو بوحدهم.</p></div>}
  <section className="sd-hero"><div><span className="sd-kicker">رحلتك إلى رخصة السياقة · B</span><h1>مرحبا {user.display_name.split(' — ')[0]}،<br/>خطوة اليوم كتفرق.</h1><p>{data.focus?'اليوم نركزو على «'+data.focus.title_ar+'».':'بدا بفكرة وحدة وخلي التقدم يجي خطوة بخطوة.'}</p><button className="sd-gold" onClick={()=>onNavigate('lessons',data.focus?.slug)}>بدء مراجعة اليوم <span>←</span></button></div><RoadArt/><div className="sd-countdown"><b>{data.days_left===null?'—':Math.max(0,data.days_left)}</b><span>{data.days_left!==null&&data.days_left<0?'فات الموعد المحدد':'يوم للموعد ديالك'}</span><button onClick={()=>{setTab('overview');setTimeout(()=>document.getElementById('sd-goal')?.scrollIntoView({behavior:'smooth'}),0);}}>تعديل الهدف</button></div></section>
  <nav className="sd-tabs" aria-label="أقسام رحلتي">{[['overview','نظرة عامة'],['performance','الأداء والتتبع'],['coach','المرافق الذكي']].map(([id,title])=><button key={id} className={tab===id?'active':''} aria-current={tab===id?'page':undefined} onClick={()=>setTab(id)}>{title}{id==='coach'&&<span>✦</span>}</button>)}</nav>
  <div className="sd-metrics">{[['◉','قراءة الدروس',`${data.completed_sections}/${data.total_sections}`,'فقرات معلّمة كمكتملة'],['↗','المعدل التجريبي',data.score===null?'—':data.score+'%',`${data.sample_size} جواب مولّد · آخر 14 يوم`],['◷','الاستمرارية',data.streak+' أيام',data.is_demo?'يشمل النشاط المولّد':'من نشاطك المسجل'],['✓','الجولات المحفوظة',data.real_session_count,'جولات مكتملة ومحفوظة']].map(([icon,label,value,note])=><article key={label}><span className="sd-metric-icon">{icon}</span><span>{label}</span><strong>{value}</strong><small>{note}</small></article>)}</div>
  {tab==='overview'&&<div className="sd-columns"><div><DailyPlan onNavigate={onNavigate} dailyMinutes={data.profile.daily_minutes}/>
   <section className="sd-panel"><div className="sd-heading"><h2>مسارك إلى الامتحان</h2><span className="sd-pill">{progress}% قراءة</span></div><div className="sd-milestones">{[['01','البداية',dateLabel(data.profile.enrolled_on)],['02','الفهم والتدريب',`${data.completed_sections} فقرة مكتملة`],['03','تقييم الاستعداد','مع التصحيح والأستاذ'],['04','موعد الامتحان',dateLabel(data.profile.exam_on)]].map(([n,t,note],i)=><div key={n} className={i<2?'current':''}><b>{n}</b><h3>{t}</h3><p>{note}</p></div>)}</div><p className="sd-note">الاستعداد: {data.readiness}. إكمال القراءة ما كيعنيش إتقان المحور.</p></section></div><aside>
   <section className="sd-coach-teaser"><span className="sd-spark">✦</span><span className="eyebrow">مرافقك فالتعلم</span><h2>نفهمو التقدم ديالك،<br/>ونختارو الخطوة الجاية.</h2><p>تحليل واضح ومراجعة مقترحة بالدارجة، مبنيين على الأرقام اللي عندنا.</p><button onClick={()=>setTab('coach')}>فتح المرافق ←</button></section>
   <section className="sd-panel" id="sd-goal"><h2>هدفي الشخصي</h2><form className="sd-goal" onSubmit={save}><label>موعد الامتحان<input type="date" value={exam} onChange={e=>setExam(e.target.value)}/></label><label>وقت المراجعة اليومي<select value={minutes} onChange={e=>setMinutes(e.target.value)}>{[5,10,15,20,30,45,60,90,120].map(n=><option key={n} value={n}>{n} دقيقة</option>)}</select></label><button className="primary" disabled={saving}>{saving?'جارٍ الحفظ…':'حفظ الهدف'}</button><p role="status">{saved}</p></form><p className="sd-note">هاد الموعد للتنظيم الشخصي، ماشي حجز رسمي.</p></section></aside></div>}
  {tab==='performance'&&<><div className="sd-columns"><section className="sd-panel"><div className="sd-heading"><div><h2>التطور خلال 28 يوم</h2><p>نقط تجريبية مولّدة، ماشي توقع للنجاح.</p></div>{data.score_change!==null&&<span className="sd-pill">{data.score_change>0?'+':''}{data.score_change} نقطة مئوية*</span>}</div><Trend days={data.timeline}/><p className="sd-note">* مقارنة متوسط آخر 14 يوم بالـ14 يوم اللي قبلها. الفراغ يعني ما كايناش معطيات.</p></section><section className="sd-panel"><h2>إيقاع المراجعة</h2><p>كل مربع نهار. النشاط التجريبي داخل فهاد العرض.</p><div className="sd-heatmap">{data.timeline.map(d=><span key={d.date} className={d.active?'done':''} title={dateLabel(d.date)+(d.active?' · نشاط مسجل':' · بدون نشاط')} aria-label={dateLabel(d.date)+(d.active?' نشاط':' بدون نشاط')}>{new Date(d.date).getDate()}</span>)}</div><p className="sd-note">◼ نشاط مسجل ◻ بلا نشاط</p></section></div>
   <section className="sd-panel"><div className="sd-heading"><h2>المحاور، واحد بواحد</h2><span className="sd-pill">عينة آخر 14 يوم</span></div><div className="sd-topic-grid">{data.topics.map(t=><article className="sd-topic" key={t.id}><div><h3>{t.title_ar}</h3><b>{t.score===null?'—':t.score+'%'}</b></div><progress max="100" value={t.score||0} aria-label={'معدل تجريبي: '+t.title_ar}/><p>{t.score===null?'باقي ما كايناش معطيات مصححة':`${t.sample} جواب تجريبي · ${t.score<65?'أولوية للمراجعة':'واصل التدريب'}`}</p><button onClick={()=>onNavigate('lessons',t.slug)}>مراجعة المحور ←</button></article>)}</div></section>
   <section className="sd-panel"><h2>سجل التدريب</h2><p>الجولات الفعلية المسجلة مؤخراً</p>{!data.real_sessions.length?<p className="sd-note">مازال ما حفظتي حتى جولة. كمل سلسلة وأنت داخل للحساب وغادي تلقاها هنا.</p>:data.real_sessions.map(s=><div className="sd-history" key={s.id}><span>✓ جولة معاينة</span><time>{dateLabel(s.recorded_at)}</time><b>{s.answered}/{s.total} مؤكد</b><button className="secondary" onClick={()=>onNavigate('training')}>فضاء التدريب</button></div>)}<details className="sd-details"><summary>آخر سجلات المحاكاة التجريبية</summary>{data.history.map((h,i)=><div className="sd-history" key={i}><span>{h.title}</span><time>{dateLabel(h.date)}</time><b>{h.score}%</b><small>مولّد</small></div>)}</details></section></>}
  {tab==='coach'&&<section className="sd-panel sd-assistant"><div className="sd-assistant-intro"><span className="sd-spark">✦</span><span className="eyebrow">نفهمو الأرقام، خطوة بخطوة</span><h2>آشنو نوجدو ليك اليوم؟</h2><p>اختار طلب. كنستعملو المعطيات ديالك باش نخرجو بتوجيه واضح للمراجعة.</p></div><div className="sd-prompts">{[['analysis','حلّل أدائي','شنو كيبان من التدريب ديالي؟'],['plan','اقترح المراجعة','على شنو نركز اليوم؟'],['motivation','شجعني نكمل','بغيت نرجع للإيقاع ديالي.']].map(([intent,title,desc])=><button key={intent} disabled={coachBusy} onClick={()=>ask(intent)}><strong>{title}</strong><span>{desc}</span></button>)}</div>{coachBusy&&<p role="status">كنوجد التوجيه ديالك…</p>}{coachError&&<p className="form-error" role="alert">{coachError}</p>}{coach&&<article className="sd-reply" aria-live="polite"><span className="sd-pill">{coach.source==='openai'?'توجيه مولّد بـ OpenAI':'توجيه حسابي محلي'}</span><p>{coach.answer}</p>{coach.source!=='openai'&&<small>{coach.reason==='not_configured'?'خدمة OpenAI ما تفعّلاتش دابا.':coach.reason==='daily_limit'?'وصلتي للحد اليومي. التوجيه الحسابي باقي متاح.':'النموذج ما جاوبش دابا؛ هادي التوصية الحسابية.'}</small>}</article>}<p className="sd-note">هاد المرافق مختص بالتقدم وتنظيم المراجعة. المساعد ديال أسئلة قانون السير غادي يتربط بالمراجع المراجعة فمرحلة مستقلة.</p></section>}
 </div>;
}


