import React,{useEffect,useState} from 'react';
import {journeyRequest} from './journey-api';
import './student-dashboard.css';
export default function StudentProgress({user,onLogin,onNavigate}){
 const [data,setData]=useState(null),[week,setWeek]=useState(null),[error,setError]=useState(''),[revision,setRevision]=useState(0),[exam,setExam]=useState(''),[minutes,setMinutes]=useState(20),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{if(!user)return;let active=true;setError('');Promise.all([journeyRequest(),journeyRequest('/notebook')]).then(([d,n])=>{if(active){setData(d);setWeek(n.week);setExam(d.profile.exam_on||'');setMinutes(d.profile.daily_minutes);}}).catch(e=>active&&setError(e.message));return()=>{active=false;};},[user?.membership_id,revision]);
 async function save(e){e.preventDefault();setBusy(true);setError('');try{await journeyRequest('/goal',{exam_on:exam||null,daily_minutes:Number(minutes)},'PUT');setMessage('تحفظ الهدف ديالك.');setRevision(n=>n+1);}catch(e){setError(e.message);}finally{setBusy(false);}}
 if(!user)return <section className="sd-welcome"><h1>التقدم ديالك، خطوة بخطوة.</h1><button className="primary" onClick={onLogin}>تسجيل الدخول</button></section>;
 return <section className="student-dashboard"><span className="eyebrow">تقدمي</span><h1>كل مجهود كيتحسب.</h1><p>هنا كتلقى القراءة والنشاط المسجلين ديالك، خطوة بخطوة.</p>{error&&<p role="alert">{error}<button className="secondary" onClick={()=>setRevision(n=>n+1)}>إعادة المحاولة</button></p>}{!data?(error?null:<p role="status">كنحمّلو التقدم…</p>):<><div className="school-metrics">{[[data.completed_sections+'/'+data.total_sections,'فقرات معلّمة كمقروءة'],[week.active_days+'/7','أيام النشاط هذا الأسبوع'],[week.runs,'تدريبات مكتملة هذا الأسبوع']].map(([v,l])=><article key={l}><b>{v}</b><span>{l}</span></article>)}</div><section className="sd-panel"><h2>نشاط آخر 7 أيام</h2><div className="notebook-days">{week.days.map(d=><span key={d.day} className={d.active?'active':''} title={d.day}>{new Date(d.day+'T12:00:00').toLocaleDateString('ar-MA',{weekday:'short'})}<b>{d.active?'✓':'·'}</b></span>)}</div><p>هاد النشاط من القراءة والتدريب المسجلين، ماشي نقطة إتقان.</p></section><section className="sd-panel"><h2>الخطوة الجاية</h2><p>شوف الجولات المحفوظة أو رجع للنقط اللي بغيتي تراجع. القراءة بوحدها ما كتثبتش الإتقان.</p><button className="primary" onClick={()=>onNavigate('training')}>عرض تدريباتي</button> <button className="secondary" onClick={()=>onNavigate('notebook')}>دفتر المراجعة</button></section><section className="sd-panel"><h2>هدفي الشخصي</h2><form className="sd-goal" onSubmit={save}><label>موعد الامتحان<input type="date" value={exam} onChange={e=>setExam(e.target.value)}/></label><label>وقت المراجعة اليومي<select value={minutes} onChange={e=>setMinutes(e.target.value)}>{[5,10,15,20,30,45,60,90,120].map(n=><option key={n} value={n}>{n} دقيقة</option>)}</select></label><button className="primary" disabled={busy}>حفظ الهدف</button><p role="status">{message}</p></form><p className="sd-note">هاد الموعد للتنظيم الشخصي، ماشي حجز رسمي.</p></section></>}</section>;
}
